semantic-systems/nfdi-search-engine

.gitignore
api.py
controller.py
dblp.py
main.py
mapping.py
merger.py
search_openalex.py
utils.py
zenodo.py

The initial modularization will be merged into development. Modularization correctly has this scheme:

Feature/modularization to Develop

---

dblp.py
merger.py
search_openalex.py
utils.py

It improves on the duplicate handling, previously would just ignore the new duplicates

Initial mergin or resourcers

---

main.py

Trigger the search if the enter key is pressed within the text field.
Addionally limit Textbox to one line.

Trigger Search on Enter

---

main.py
templates/result.html

No results found was also added

Only shows title of category if there are results in that category

---

main.py
search_dblp.py
search_openalex.py

I have made changes to remove, change and add comments on the following files:
main.py
search_dblp.py
search_openalex.py
Please review the changes and merge this pull request if everything looks good.

Clean up comments

---

main.py
requirements.txt
search_wikidata.py

Feature 39 wikidata search

---

main.py
objects.py
search_cordis.py
search_gesis.py
templates/result.html

**Description:**
This pull request aims to integrate GESIS and CORDIS into the NFDI search engine, enhancing and enriching its functionality.
_Changes Made:_
- Added new file: search_cordis.py
- Added new file: search_gesis.py
- Updated main.py
- Updated objects.py
- Updated templates/result.html
The relevant parts of the project have been synchronized and updated to support the integration.

Integration of GESIS and CORDIS into NFDI search engine

---

search_wikidata.py

Added Search for Persons; Query improvements

Feature: #39 - Wikidata-Search - Part2

---

templates/footer.html

- new link button has been added in the footer (connect block) to reach out to us using the following email:
nfdi4ds.inf@lists.uni-hamburg.de

added write to us link in the footer

---

cordis.py
dblp.py
gesis.py
main.py
merger.py
openalex.py
wikidata.py
zenodo.py

- Updated threading script in the main.py file
- Source file names have been modified to just the source name such as dlbp.py, openalex.py, gesis.py etc.
- primary method in those files have been renamed to 'search'

updated main.py file, and renamed all the sources files 

---

gesis.py
main.py
templates/result.html

The GESIS API has been re-tested and synchronized with all relevant parts of the project to ensure seamless integration.
Please review the changes and merge this pull request if everything appears to be in order.
Thank you

Re-tested GESIS API Integration

---

static/css/result.css
static/css/search_box.css
templates/index.html
templates/search_layout.html

If someone tries to search without typing anything in, there is a little message below the search bar to "Please enter a search term".
I've changed it in the two places, where the search bar is implemented and added a little css to the corresponding files.
Please review and merge.

Prevent empty search

---

gepris.py
main.py
objects.py
templates/result.html

This pull request contains the integration of GEPRIS issue#60 [Integrate GEPRIS#60](https://github.com/semantic-systems/nfdi-search-engine/issues/60)
Please review the changes and merge this pull request if everything is fine.
Thank you,

gepris-integraton

---

main.py
objects.py
sources/gesis.py
templates/components/resources.html
templates/resource-details.html
templates/results.html

This pull request includes the following changes:
- Resources tab of the new layout.
- Mapped GESIS to the new schema.
Changes Made:
- main.py
- objects.py
- sources/gesis.py
- templates/results.html
Files Created/Added:
- templates/components/resources.html
- templates/resource-details.html
Please review and merge this pull request if everything is in order. Thanks!

Resources-Tab of the new layout and GESIS mapping to the new schema.

---

main.py
sources/ieee.py

updated IEEE to schema.org mapping and new attributes added.

New layout mapping

---

main.py
objects.py
sources/cordis.py
templates/components/resources.html

CORDIS updated to schema.org mapping.

cordis updated to schema.org mapping

---

objects.py
sources/cordis.py
templates/components/resources.html

More attributes add and updated based on the schema.org mapping.

cordis projects' attributes updated and mapped to the schema.org

---

main.py
objects.py
sources/gepris.py
sources/zenodo.py
templates/components/resources.html

This pull request includes GEPRIS mapping to schema.org and resolves a KeyError issue in the Zenodo file. the bag was related to the 'keywords' key in the response data from the Zenodo API.

GEPRIS mapping to schema.org and Zenodo bug fix

---

sources/cordis.py
sources/zenodo.py
templates/components/fundings.html
templates/components/organizations.html
templates/results.html

This pull request contains the development and adaption of the "Fundings" tab of the new layout design and mapping "cordis" data to the "Fundings" tab. Here's a detailed overview of the updates:
Modified Files:
sources/cordis.py
templates/components/organizations.html
templates/results.html
New Added File:
templates/components/fundings.html: a new HTML file has been added to manage fundings and project information.

fundings-tab adjustment and cordis mapped to fundings

---

main.py
objects.py
sources/codalab.py
sources/cordis.py
templates/components/resources.html

This pull request includes the integration of Codalab, which has already been mapped to schema.org.

Integration of Codalab with schema.org mapping

---

sources/eudat.py

I changed the language type from str to list, to fix the wrong representation of the language tag.

Bugfix: The language as represented wrongly.

---

main.py

I noticed the researcher details page was throwing an error, it seems that these lines of code got lost in a merge a few commits ago, so I added them back in.

researcher details page hotfix

---

templates/components/chatbox.html
templates/results.html

I've made small changes, so that the chat-robot is collapsed at first and can then be expanded.
Please review and merge if you don't see any problems.

collapse chatbox at first

---

main.py
objects.py
requirements.txt
sources/eulg.py
static/css/style.css
templates/components/chatbox.html
templates/components/resources.html
templates/organization-details.html
templates/publication-details.html
templates/researcher-details.html
templates/results.html

- few hotfixes - one on the researcher details page and chatbot visibility on the results page loads
- few cosmetic changes - styling changes to adjust the layout for tablets and other screen sizes

Merge develop to main branch

---

sources/codalab.py
sources/cordis.py
sources/gepris.py
sources/gesis.py
sources/ieee.py

Hi Rana,
This pull request includes the timeout handling for Codalab, CORDIS, GEPRIS, and IEEE, as we discussed. You can review and adjust it with the other resources that you already updated, and when everything looks good, please merge it into the Develop branch.
Thank you.

timeouts handled in Codalab, Cordis, Gepris and Ieee

---

config.yaml
main.py
sources/codalab.py
sources/cordis.py
sources/dblp.py
sources/eudat.py
sources/eulg.py
sources/gepris.py
sources/gesis.py
sources/ieee.py
sources/oersi.py
sources/openaire.py
sources/openalex.py
sources/orcid.py
sources/resodate.py
sources/wikidata.py
sources/zenodo.py
static/css/style.css
templates/index.html
templates/results.html

I've implemented the top paginator. I've tried to make it responsive to different screen sizes and portrait mode. In portrait mode the bottom of the table looks a bit crowded but it's the best I could do, so that all the information still fits.
Please give me feedback or merge it if you don't see any issues.

add top paginator

---

static/css/style.css
templates/index.html

few styles have been adjusted to make the layout more responsive for the Gateway landing page

layout adjustments

---

templates/includes/footer.html

Updated footer impressum and Dataschutz links to Leuphana.de

updated footer links

---

main.py
requirements.txt
sources/data_retriever.py
templates/components/publications.html
templates/components/researchers.html

- chatbot flag in the config.yml file was treated as string, which in fact should be treated as a boolean value.

Fix chatbot issue

---

config.py
main.py
sources/openalex_publications.py
templates/partials/search-results/events.html
templates/partials/search-results/organizations.html
templates/partials/search-results/others.html
templates/partials/search-results/projects.html
templates/partials/search-results/publications.html
templates/partials/search-results/researchers.html
templates/partials/search-results/resource-block.html
templates/researcher-details.html
templates/results.html

Updated search results layout
researcher details page layout

 search results layout

---

sources/wikidata_publications.py
sources/wikidata_researchers.py

The SPARQL in wikidata_publication and wikidata_researcher are updated.

Enhance wikidata search

---

templates/layouts/base.html
templates/partials/search-results/researchers.html
templates/publication-details.html
templates/researcher-details.html

Updated researcher details page

Enhancements

---

templates/partials/search-results/others.html
templates/partials/search-results/publications.html
templates/partials/search-results/resource-block.html
templates/publication-details.html
templates/researcher-details.html

Relevant issue: https://github.com/semantic-systems/nfdi-search-engine/issues/271

Updated author chips

---

requirements.txt

to fix the security issues, updated the following packages:
- gunicorn
- werkzeug
- requests

fixed security issues

---

requirements.txt

fixed security alert for gunicorn

---

requirements.txt

To address security vulnerabilities, upgraded the following Flask packages:
- Flask
- flask-login
- flask-session
- flask-wtf
Werkzeug will be auto-updated, as this was the package having the core security issue.

Update Flask packages to fix security vulnerabilities
